### ISSUE TITLE
Hi,Are there any paper suggested for  this code?

### ISSUE THREAD

**Issue by xjrelc** [strongio/torch-kalman#38]
The paper i see is:
1.Allik_Bethany_PhD
2.USING KALMAN FILTER AND TOBIT KALMAN FILTER IN ORDER TO IMPROVE THE MOTION RECORDED BY KINECT SENSOR

But troble came to the formular when calculating E(y_k | x_k),Can you give me in formular way of the code function(_F1F2) in utils.py, or any paper having this code formular.

Thanks a lot!!

**Comment by jwdink** [comment]
I've added a link at ecc6998d973addb8a14171012887076b5743def2. That repo is cited in the wikipedia page on truncated normal, but for some reason the PDF file explaining the method was removed from master, so had to do some digging to find it.
